---
- name: "restart zabbix"
  systemd: { name: zabbix-server, state: restarted }

- name: "restart nginx"
  systemd: { name: nginx, state: restarted }

- name: "restart php-fpm"
  systemd: { name: php8.3-fpm, state: restarted }
