- name: Install dependencies for Grafana
  apt:
    name: [apt-transport-https, software-properties-common, wget]
    state: present

- name: Add Grafana GPG key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.key
    mode: '0644'

- name: Add Grafana Repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.key] https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Start and Enable Grafana Service
  systemd:
    name: grafana-server
    enabled: yes
    state: started

# --- PHẦN CÀI ĐẶT PLUGIN BỔ SUNG ---

- name: Ensure Grafana plugins directory exists with correct ownership
  file:
    path: /var/lib/grafana/plugins
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'

- name: Install NOC and Zabbix Plugins
  grafana_plugin:
    name: "{{ item }}"
    state: present
  loop:
    - "alexanderzobnin-zabbix-app"      # Plugin kết nối Zabbix
    - "knightss27-weathermap-panel"     # Sơ đồ tải mạng (Weathermap)
  register: plugin_status

- name: Restart Grafana to activate plugins
  systemd:
    name: grafana-server
    state: restarted
  when: plugin_status.changed