---
- name: "Full Cleanup: Remove Monitoring Stack with Confirmation"
  hosts: monitoring_server
  become: yes

  # --- Warning ---
  vars_prompt:
    - name: "confirm_delete"
      prompt: "\n!!! WARNING !!!\nThis command will PERMANENTLY DELETE Zabbix, MariaDB, Nginx and ALL DATA.\nAre you sure you want to continue? (Type 'yes' to confirm)"
      private: no 

  tasks:
    - name: "Checking confirmation"
      meta: end_play
      when: confirm_delete | lower != 'yes'

    - name: "Stopping services"
      systemd:
        name: "{{ item }}"
        state: stopped
      loop: [zabbix-server, zabbix-agent, nginx, mariadb, grafana-server, php8.3-fpm]
      ignore_errors: yes

    - name: "Purging packages and configs"
      apt:
        name: 
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - zabbix-release
          - mariadb-server
          - mariadb-common
          - nginx
          - "php8.3*"
          - grafana
        state: absent
        purge: yes
      
    - name: "Deleting data directories (Permanent)"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/zabbix
        - /etc/nginx
        - /etc/mysql
        - /var/lib/mysql
        - /var/lib/zabbix
        - /var/log/zabbix
        - /usr/share/zabbix

    - name: "Cleaning up Apt"
      apt:
        autoremove: yes
        update_cache: yes

    - name: "Notify Success"
      debug:
        msg: "The system has been cleaned up. You can reinstall from scratch now"
