- name: Install MariaDB Server
  apt:
    name: ["mariadb-server", "python3-pymysql"]
    state: present
    update_cache: yes

- name: Start MariaDB
  systemd: { name: mariadb, state: started, enabled: yes }

- name: Create Zabbix DB
  mysql_db:
    name: zabbix
    encoding: utf8mb4
    collation: utf8mb4_bin
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Create Zabbix User
  mysql_user:
    name: zabbix
    password: "{{ zabbix_db_pass }}"
    priv: "zabbix.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
